{
 "title": "Overview Authoritative Servers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queries Totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  nqueries AS \"$LABEL\"\nFROM authserver\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = '$SERVER_NAME'\n  and ipv=$IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RTT (TCP only)",
   "type": "graph",
   "description": "RTT measured from TCP hadshakes\nAVG per server and IP version",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  avg_rtt AS \"$LABEL\"\nFROM authserver\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = '$SERVER_NAME'\n  and ipv=$IPV\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Unique Resolvers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  resolvers AS \"$LABEL\"\nFROM authserver\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = '$SERVER_NAME'\n  and ipv=$IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unique ASes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  ases AS \"$LABEL\"\nFROM authserver\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = '$SERVER_NAME'\n  and ipv=$IPV\nORDER BY 1"
    }
   ]
  }
 ]
}