{
 "title": "ASes and Hypergiants",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hyper Giants - Queries - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  queries AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - Queries - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  queries AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - RTT - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  avg_rtt AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - RTT - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  avg_rtt AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - Anycast Sites - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "sites" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  sites AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - Anycast Sites - $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "sites" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  sites AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - Resolvers -  $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "resolvers" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  resolvers AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hyper Giants - Resolvers -  $IPV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "resolvers" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  resolvers AS \"$AS_NAME-$AS_NUMBER-$SERVER_NAME_$IPV\"\nFROM ASes\nWHERE\n  $__timeFilter(epoch_time) AND\n  asn = '$AS_NUMBER' AND\n  ipv= $IPV\nORDER BY 1"
    }
   ]
  }
 ]
}