{
 "title": "debug-server",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "ns1.dns.nl - Queries - IPv4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  nqueries AS \"$LABEL\"\nFROM anycastSites\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = '$SERVER_NAME'\n  and ipv=$IPV \n  and server_location='$SITE'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ns1.dns.nl - RTT (TCP)  - IPv4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  avg_rtt AS \"London\"\nFROM anycastSites\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = 'ns1.dns.nl'\n  and ipv=4\n  and server_site='london'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ns1.dns.nl - Resolvers - IPv4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  resolvers AS \"London\"\nFROM anycastSites\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = 'ns1.dns.nl'\n  and ipv=4\n  and server_site='london'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ns1.dns.nl - ASes - IPv4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  epoch_time AS \"time\",\n  ases AS \"London\"\nFROM anycastSites\nWHERE\n  $__timeFilter(epoch_time) AND\n  server_name = 'ns1.dns.nl'\n  and ipv=4\n  and server_site='london'\nORDER BY 1"
    }
   ]
  }
 ]
}